### ISSUE TITLE
Add button in VideoOSD.xml to activate osdcmssettings

### ISSUE THREAD

**Issue by jingai** [jingai/skin.metropolis#109]
See http://forum.kodi.tv/showthread.php?tid=250862&pid=2411911#pid2411911

**Comment by jingai** [comment]
This requires an additional icon.  Pushing off for now.

**Comment by MacGyverr** [comment]
https://github.com/MacGyverr/skin.metropolis/commit/a54a3ef36d9b766d0350ccb8f000c1ef1078a8b0
