### ISSUE TITLE
Add link to Extended Info in DialogVideoInfo

### ISSUE THREAD

**Issue by jingai** [jingai/skin.metropolis#111]
As Estuary does.

**Comment by MacGyverr** [comment]
Done, per user request.
https://github.com/MacGyverr/skin.metropolis/commit/045d5d1c00324e4c9fcb061ba35a0a6b3a41d987

**Comment by jingai** [comment]
Is this addon still available at this point?

**Comment by jingai** [comment]
I guess it's fine even if it isn't, as it shouldn't do any harm leaving it in there.
