### ISSUE TITLE
Clean up/verify PVR skinning

### ISSUE THREAD

**Issue by jingai** [jingai/skin.metropolis#113]
Use "PVR Demo" addon.  Make sure widget functions properly too.

**Comment by jingai** [comment]
MyPVRGuide: when scrolling through the guide, it leaves 'trails' of previously-focused items.  Also, there is a scrollbar in the XML, but I've no idea how to actually get to it to test it..

**Comment by MacGyverr** [comment]
The scroll-bar is for any view other than "Timeline" in the guide.
https://github.com/MacGyverr/skin.metropolis/commit/a96eebb43d5efd87f872e12848ab3bb08f34eaee

**Comment by jingai** [comment]
How do you get to something other than Timeline with the demo addon?

**Comment by MacGyverr** [comment]
You go all the way to the left (like 24 hours back) or all the way to the right (48 hours ahead) and the side menu will pop up.  It's best we can do when there is a 4-way fullscreen control.  The top, and down are an infinite loop, but the sides do have limits.

**Comment by jingai** [comment]
Yeah, I figured that, I just didn't realize MyPVRGuide.xml was common with others.  This is honestly my first time even seeing the PVR stuff.

**Comment by jingai** [comment]
The only thing left (I believe) for this is the 'ghosting' issue in MyPVRGuide.xml, where it leaves trails of previously-focused items.

https://github.com/MacGyverr/skin.metropolis/commit/a96eebb43d5efd87f872e12848ab3bb08f34eaee didn't fix this (just noting it here for myself).

edit: Nevermind.. apparently this is a problem with Estuary too, so I'm going to assume it's a core issue.
