### ISSUE TITLE
Overlay/Media Flag for 3D movies

### ISSUE THREAD

**Issue by jingai** [jingai/skin.metropolis#114]
Add either (or both) an Overlay (like the Watched Overlay) or a Media Flag indicating that a video is 3D.  Perhaps indicate the type of 3D, as well.

Requested at http://forum.kodi.tv/showthread.php?tid=290668

**Comment by MacGyverr** [comment]
https://github.com/MacGyverr/skin.metropolis/commit/93ae62038b599cbc77eeba95a94668804d9b4445

**Comment by jingai** [comment]
Thanks @MacGyverr
