### ISSUE TITLE
Changes to Skin Helper Service need to be addressed. 

### ISSUE THREAD

**Issue by MacGyverr** [jingai/skin.metropolis#139]
User says it throws these errors with Kodi 17.5.

23:53:04.405 T:4136 WARNING: Skin Helper Service --> Deprecated method: recentmovies. Please reassign your widgets to get rid of this message. -This automatic redirect will be removed in the future
23:53:05.224 T:2224 WARNING: Skin Helper Service --> Deprecated method: recentmusicvideos. Please reassign your widgets to get rid of this message. -This automatic redirect will be removed in the future
23:53:05.965 T:7964 WARNING: Skin Helper Service --> Deprecated method: recentepisodes. Please reassign your widgets to get rid of this message. -This automatic redirect will be removed in the future
23:53:08.010 T:2664 WARNING: Skin Helper Service --> Deprecated method: favourites. Please reassign your widgets to get rid of this message. -This automatic redirect will be removed in the future

**Comment by Angelinas1** [comment]
This skin use old method to call widgets...
old method:
`plugin://script.skin.helper.service/?action=recentalbums&amp;limit=25&amp;reload=$INFO[Window(Home).Property(widgetreloadmusic)]`
regular method:
`plugin://script.skin.helper.widgets/?action=recent&amp;mediatype=albums&amp;reload=$INFO[Window(home).Property(widgetreload-music)]`
change in skin (widgetPath), and you will get rid of kodi log notice "WARNING: Skin Helper Service".

**Comment by jingai** [comment]
I'll fix it soon.

**Comment by MacGyverr** [comment]
https://github.com/MacGyverr/skin.metropolis/commit/274376704b7b7d0c721515a74a61cc946a318586

**Comment by jamesc2151** [comment]
umm here is the real problem i be-leave  it can't find the plugin at all for some reasion.. I love your skin and want everything to work so I do a new minimal install of the latest osmc/kodi of a raspberry p ... here is the log stating it can't find the pluging  **"**  

 ERROR: GetDirectory - Error getting plugin://script.skin.helper.service/?action=recentmusicvideos&reload=
03:21:19.259 T:1246331648   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>**"**  

Does this when you touch Movie or music labels from main menu..

Thanks for you hard work...

James

**Comment by MacGyverr** [comment]
The fix was for the changes needed for Kodi 18, per the authors instructions.  
I'm not sure if they would also apply to Kodi 17.

**Comment by jamesc2151** [comment]
By Going back and doing a forced update on dependent plug-ins it fixed the
issue, I 1st un-installing the helper plug-in  and a reboot. then the
dependents update and then the helper.. Worked first time without a reboot
and has been doing fine sense... I thank you for your time and response..

**Comment by jingai** [comment]
Seems Skin Helper is no longer available?

**Comment by jingai** [comment]
@MacGyverr, do you know the situation here with Skin Helper?  I've been away for so long.. but, it seems Marcel left Kodi development and this addon isn't in the official repo any more?

If the above is a true statement, I'm wondering if we should change the default widgets to use the built in stuff so it doesn't confuse new users?

**Comment by Angelinas1** [comment]
https://github.com/kodi-community-addons/repository.marcelveldt/raw/master/repository/repository.marcelveldt/repository.marcelveldt-1.0.3.zip

**Comment by MacGyverr** [comment]
I think some users pointed out that it wasn't working, I noticed the same thing, I showed them how to use the built-in Kodi versions, but those are missing certain features if I recall.

**Comment by jingai** [comment]
Yeah, probably should move the defaults to the built-in widgets, but in the interest of getting _anything_ out for a recent version of Kodi, I'll push this off until 4.1.

**Comment by jingai** [comment]
Went ahead and did this.
