### ISSUE TITLE
Video OSD on movies shows screen capture instead of poster.

### ISSUE THREAD

**Issue by jingai** [jingai/skin.metropolis#148]
In lower-left corner.  Frame shows it is supposed to be a poster, but instead a screen capture from the movie is displayed there.

**Comment by MacGyverr** [comment]
As pointed out by scoonbag in the [kodi forum](https://forum.kodi.tv/showthread.php?tid=362740&pid=3053533#pid3053533), this will fix it.
In the file includes.xml file, line 1598 needs to be changed to:
`<texture background="true">$INFO[Player.Art(poster)]</texture>`
and lines 1600 and 1610 need to be changed to:
`<visible>VideoPlayer.Content(Movies) + !String.StartsWith(Player.Art,default)</visible>`

**Comment by jingai** [comment]
Fixed.
