### ISSUE TITLE
[Request] HDR and SDR Flags

### ISSUE THREAD

**Issue by theHornest** [jingai/skin.metropolis#159]
Thank you in advance for your work,
the skin gives me a lot of pleasure.
Unfortunately, I miss the HDR and SDR flags in my 4K films.
It would be great if you could build this in.

**Comment by MacGyverr** [comment]
Created flags and code fix for missing HDR flags.
https://github.com/jingai/skin.metropolis/commit/7bece0dbf867bd6c479815cc18d78a2c33f8f835
![Capture23](https://github.com/jingai/skin.metropolis/assets/6500800/71bbc39c-11e4-414b-bd16-c52247b03f10)

**Comment by jingai** [comment]
Will be addressed in next release.
