### ISSUE TITLE
Hide Movie/TV Watched Status

### ISSUE THREAD

**Issue by markrennie71** [jingai/skin.metropolis#176]
I liked having this but it now appears on my home page for the series/seasons. Is there a way to remove it from the Home page but still have it for each series/season please?

Cheers

**Comment by MacGyverr** [comment]
I believe I fixed it with this:
https://github.com/jingai/skin.metropolis/pull/177/commits/be34b58fbec809e9978bb24347361f1bcf9e79c8

**Comment by markrennie71** [comment]
> I believe I fixed it with this: [be34b58](https://github.com/jingai/skin.metropolis/commit/be34b58fbec809e9978bb24347361f1bcf9e79c8)

Perfect, thank you
