### ISSUE TITLE
DTS-HD, DTSHRA, DTSHD-HRA Media Flags

### ISSUE THREAD

**Issue by jingai** [jingai/skin.metropolis#24]
Currently missing.

**Comment by MacGyverr** [comment]
![dtshd_hra](https://user-images.githubusercontent.com/6500800/49677972-7ac97080-fa36-11e8-88f1-5441e6bcd7ed.png)
![dts_hra](https://user-images.githubusercontent.com/6500800/49677973-7ac97080-fa36-11e8-92d6-d667d07b1737.png)
