### ISSUE TITLE
zorder fixes

### ISSUE THREAD

**Issue by jingai** [jingai/skin.metropolis#28]
http://forum.kodi.tv/showthread.php?tid=231270&pid=2052081#pid2052081

https://github.com/MacGyverr/Metropolis/commit/0119b9c7d9ceb8b2fddf9f0566701c73df3cc6ab

**Comment by jingai** [comment]
Backport to Isengard too.

**Comment by jingai** [comment]
Will need to thoroughly verify this as the one zorder tag we use was put there intentionally to get skin.shortcuts dialogs (and I think others) to show properly..

**Comment by MacGyverr** [comment]
zorder has been remove from all windows at this point
