### ISSUE TITLE
DSP support

### ISSUE THREAD

**Issue by jingai** [jingai/skin.metropolis#30]
http://forum.kodi.tv/showthread.php?tid=231270&pid=2056843#pid2056843

https://github.com/MacGyverr/Metropolis/commit/d5bd430cf14e8ea1e873c5ed8fe0f7b6fdd7ab3b

**Comment by MacGyverr** [comment]
DSP Support has been removed from Kodi now as of Kodi 18

https://forum.kodi.tv/showthread.php?tid=298565&pid=2467935#pid2467935
