### ISSUE TITLE
Support for Image Resource addons

### ISSUE THREAD

**Issue by jingai** [jingai/skin.metropolis#54]
So we don't have to ship the various media flags, weather icons, etc with the skin.

Could depend on resource.images.studio.white, for example.

See:  http://forum.kodi.tv/showthread.php?tid=231270&pid=2052076#pid2052076

https://github.com/MacGyverr/skin.metropolis-personal/commit/b255184ef19b15c486b66976ce81948b3429efd6

https://github.com/MacGyverr/skin.metropolis-personal/commit/a4cd05a7f49721a8370632cc833b79a98ae572dc

https://github.com/MacGyverr/skin.metropolis-personal/commit/3f632272b4436e477c6fbc613af08fe34c8c00f9

https://github.com/MacGyverr/skin.metropolis-personal/commit/ddce014767938909d8f4d1b365d2731cc0df9220

https://github.com/MacGyverr/skin.metropolis-personal/commit/55b3dcbd5ff4db20680ca8ca43e228d1f37a3c0c

https://github.com/MacGyverr/skin.metropolis-personal/commit/d73272084c0fcea97ca5d470dbb653db047ee22a

**Comment by MacGyverr** [comment]
Newest ones here:
https://github.com/MacGyverr/skin.metropolis/commit/94136a2dd647b401d0c7efe87cf3ca49724887ad

**Comment by jingai** [comment]
https://github.com/MacGyverr/skin.metropolis/commit/54b0ae8ee1dfa424a5a81b26ab9f715824aecad4

**Comment by jingai** [comment]
https://github.com/MacGyverr/skin.metropolis/commit/6f8adeb7164c19d9a7b82353557f6744b7bf1284

**Comment by jingai** [comment]
https://github.com/MacGyverr/skin.metropolis/commit/46853af06a1b069857edf6f2121fb353b61ff2da
