### ISSUE TITLE
Option to prefer ListItem.UserRating over scraped rating in media flag

### ISSUE THREAD

**Issue by jingai** [jingai/skin.metropolis#55]
See: http://forum.kodi.tv/showthread.php?tid=231270&pid=2135449#pid2135449

**Comment by MacGyverr** [comment]
https://github.com/MacGyverr/skin.metropolis/commit/d9a4ce78257778fcbf9ed23a0ef200b2f169b3d7
and
https://github.com/MacGyverr/skin.metropolis/commit/a7560e932d4d788fbc0841a65e8e8e6018cf1114
