### ISSUE TITLE
Show current add-on name and version in global heading

### ISSUE THREAD

**Issue by jingai** [jingai/skin.metropolis#6]
If possible. Around line 157 in Includes.xml.

Probably need to re-think the way the Global_Heading is done entirely.. should perhaps do it all how Confluence does it for consistency (grep WindowTitleCommons).

But, it appears Container.FolderName or PluginName might be what I was looking for (http://wiki.xbmc.org/index.php?title=InfoLabels#Container)

**Comment by MacGyverr** [comment]
This does this.  (and more, but can be scaled back if it is too extreme)
https://github.com/MacGyverr/skin.metropolis/commit/a56ad11d6c6fd50147c5d4020f741db295287479

**Comment by jingai** [comment]
And https://github.com/MacGyverr/skin.metropolis/commit/5d1682a77f8809b6870116bedba297b45a4f4f78
