### ISSUE TITLE
Add DialogGameControllers

### ISSUE THREAD

**Issue by jingai** [jingai/skin.metropolis#61]
See http://forum.kodi.tv/showthread.php?tid=250862&pid=2279680#pid2279680

**Comment by jingai** [comment]
https://github.com/xbmc/xbmc/commit/7564cc2ff889f4e86fa27e128a667f137a204a6e

**Comment by MacGyverr** [comment]
This is in my Retroplayer build, see the bottom for screenshots. (https://github.com/MacGyverr/skin.metropolis/commit/6025a03610bb25eaff03d70d8e2519cba48d6b92)
I pondered for an hour over what a three area window should look like in Metropolis, this was the best I could come up with.  I'm no artist, so you might have to think up a better looking window.

**Comment by jingai** [comment]
How about copying the Skin Shortcuts dialog layout?  Put the OK, Reset, and Get More buttons at the bottom and keep the controller list on the left.  It would provide for more space for the button configuration, so you wouldn't be forced to overlap the top area.

**Comment by MacGyverr** [comment]
I thought of that, but that view didn't seem very in line with Metropolis either.  I'll see what I can do about converting it.

**Comment by jingai** [comment]
Well, yeah, it's not quite the same as the other dialogs, but we need an exception for dialogs that present so much information at once.  I personally think the Skin Shortcuts skin fits that bill and would be fine to carry over to other dialogs.

I'm open to other ideas as well, but I do think there should be consistency; i.e., if you do something different with the game controller dialog, we should probably make the same changes to the skin shortcuts dialog.

**Comment by MacGyverr** [comment]
new one looks like this
https://user-images.githubusercontent.com/6500800/34463908-2062ce8e-ee20-11e7-8c1f-4377721265b9.png
