### ISSUE TITLE
Replace deprecated infobools IsEmpty, StringCompare, SubString, IntegerGreaterThan

### ISSUE THREAD

**Issue by jingai** [jingai/skin.metropolis#62]
Will be removed by Kodi 18.

See http://forum.kodi.tv/showthread.php?tid=250862&pid=2281321#pid2281321

**Comment by jingai** [comment]
Actually, I'm going to push this off a bit so as to not make Jarvis updates even harder to deal with.

**Comment by MacGyverr** [comment]
These should be completely removed at this point. They have all been replaced with the newer versions in Leia.
